# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 George Saliba <george.saliba@salitronic.com>
"""Build script: lints every .pas file, then concatenates them into
Altium_MCP.pas. Lint errors abort the build so known-bad DelphiScript
patterns (Cardinal() casts, .Add(''), malformed hex, etc.) can't slip
through to a deploy cycle. Pass --skip-lint to override."""
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Files in correct declaration order
FILES = [
    'Main.pas',
    'Utils.pas',
    'Application.pas',
    'Project.pas',
    'Library.pas',
    'PCBGeneric.pas',
    'PCB.pas',
    'Generic.pas',
    'Audit.pas',
    'StatusForm.pas',
    'Dispatcher.pas',
]

OUTPUT = os.path.join(SCRIPT_DIR, 'Altium_MCP.pas')


# Lint gate. Walks the same FILES list before producing the merged unit.
if '--skip-lint' not in sys.argv:
    from lint import run_lint
    error_count = run_lint([os.path.join(SCRIPT_DIR, f) for f in FILES])
    if error_count:
        print(f'\nbuild aborted: {error_count} lint error(s). '
              'Fix them or re-run with --skip-lint to bypass.',
              file=sys.stderr)
        sys.exit(1)

header = """{ SPDX-License-Identifier: Apache-2.0                                   }
{ Copyright (c) 2026 George Saliba <george.saliba@salitronic.com>                                      }
{..............................................................................}
{ Altium_MCP.pas - Monolithic build of all Altium integration bridge               }
{ AUTO-GENERATED by build.py - Do not edit directly.                         }
{ Edit the individual .pas source files and re-run build.py instead.         }
{..............................................................................}

"""

with open(OUTPUT, 'w', encoding='utf-8') as out:
    out.write(header)
    for fname in FILES:
        path = os.path.join(SCRIPT_DIR, fname)
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        out.write(f'{{=== {fname} ===}}\n')
        out.write(content)
        if not content.endswith('\n'):
            out.write('\n')
        out.write('\n')

print(f'Built {OUTPUT}')
print(f'Total files: {len(FILES)}')
size = os.path.getsize(OUTPUT)
print(f'Output size: {size} bytes')
