# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 George Saliba <george.saliba@salitronic.com>
"""The user-facing documentation, as one set.

The README used to be the whole of it: 1031 lines and 18000 words, of
which GitHub renders only the first part, so half the content was
invisible on the repository front page. Three sections carrying more
than half the file moved out, and the guards that read the README had to
follow them.

They cannot simply point at the README any more, because a tool named in
BACKENDS or PART_SOURCING is exactly as much a promise to a reader as
one named in the README, and a guard that stops looking at it stops
protecting it. So the set is named in one place and every documentation
guard reads the same list.

TOOL_REFERENCE is GENERATED by scripts/gen_tool_reference.py and cannot
drift from the code, which is why the README's hand-curated copy of it
was deleted rather than moved. It is included here so a name check sees
it, not because it needs policing.
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]

README = ROOT / "README.md"
BACKENDS = ROOT / "docs" / "BACKENDS.md"
PART_SOURCING = ROOT / "docs" / "PART_SOURCING.md"
TOOL_REFERENCE = ROOT / "docs" / "TOOL_REFERENCE.md"

#: Everything a reader is expected to find their answer in. Order is the
#: reading order, not a priority.
DOC_FILES: tuple[pathlib.Path, ...] = (
    README,
    BACKENDS,
    PART_SOURCING,
    TOOL_REFERENCE,
)

#: The hand-written ones. TOOL_REFERENCE is excluded: it is regenerated
#: from the code, so a claim in it cannot be wrong about the code, and
#: including it would let a generated mention satisfy a guard that meant
#: to check what a human wrote.
PROSE_FILES: tuple[pathlib.Path, ...] = (README, BACKENDS, PART_SOURCING)


def _read(paths) -> str:
    parts = []
    for path in paths:
        if not path.exists():
            raise AssertionError(
                f"{path.relative_to(ROOT)} is named in the documentation "
                f"set and does not exist. Either restore it or remove it "
                f"from tests/documentation_set.py, because a guard that "
                f"silently skips a missing file protects nothing.")
        parts.append(path.read_text(encoding="utf-8", errors="replace"))
    return "\n".join(parts)


def all_text() -> str:
    """Every documentation file, concatenated."""
    return _read(DOC_FILES)


def prose_text() -> str:
    """The hand-written documentation, concatenated."""
    return _read(PROSE_FILES)
